version: "3.8"
services:
  redis:
    image: redis:alpine
    networks:
      - spring-boot-redis-network
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
  web-service:
    image: avisekhazra/movie-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8089"
    networks:
      - spring-boot-redis-network
    depends_on:
      - redis
networks:
  spring-boot-redis-network:
    driver: bridge